### ISSUE TITLE
SDK 19 - android 4.4 crash after start

### ISSUE THREAD

**Issue by pete111** [abrenoch/hyperion-android-grabber#28]
Hi, I saw min SDK version is 19 for mobile. I installed app on 4.4.2 but when I click on app icon it crashed immediatelly. Any idea please?

**Comment by abrenoch** [comment]
I would have to have a bug report or something to say for certain, but I don't see anything new in the past 24 hours in the google play console (where it should be).

Could you make sure you have 'usage & diagnostics' enabled and try again?

https://support.google.com/accounts/answer/6078260?hl=en

Hopefully that will get me the info I need!

**Comment by pete111** [comment]
done. I opened app several times, hopefully, you will be able to see some reports.

**Comment by abrenoch** [comment]
Hmm, I'm still not seeing any reports. Odd.

Mind trying the actual beta channel? Of course this is only for mobile at the moment - android TV apps require some modifications to be eligible to install on those devices.

https://play.google.com/apps/testing/com.abrenoch.hyperiongrabber

**Comment by pete111** [comment]
well,I think I am doing something wrong with installation and that is why you don't see it. I installed the newest apk from https://github.com/abrenoch/hyperion-android-grabber/releases. When I open https://play.google.com/apps/testing/com.abrenoch.hyperiongrabber it shows me that I am not available to see it "A testing version of this app hasnt been published yet or isnt available for this account". Could you please tell me what to do to help you debug the app?

**Comment by abrenoch** [comment]
Hey pete, sorry about that, I though that URL was the address where you could sign up for testing, but I guess not. First you will need to sign-up for the google+ community I just made (I wish there was a better way), then use the link I sent earlier and you should be able to get it installed via the play store!

https://plus.google.com/communities/101526321905444484496

Please let me know if you have any trouble!

**Comment by pete111** [comment]
Hi @abrenoch, you are great! Thanks for your further info. My fault, this is my first time to become tester :) Sorry. I did the steps and installed it via link successfully. Then I opened app and it crashed so I clicked on "Report" button, so hopefully you got report ok. By the way on Tv with 5.1.1 it works ok. 
By the way, I found out that contect on TV via youtube or hardware accelerated vieweng, antenna signal etc is not processed by your app. Do you think rooting the device could help?

**Comment by abrenoch** [comment]
All good pete, we are learning together!

I'll be sure to let you know what seems to be the problem when I get the report (I guess they can take up to a day sometimes to show up)... I _think_ everything you did should help!

For the apps not grabbing, I just can't say with any confidence that I know what is going on there yet unfortunately. Different devices could certainly be doing things that I simply have not seen with my hardware.

You can try this alternate youtube app to see if that one works: https://smartyoutubetv.github.io/

I'm not certain if root would help yet or not (you would need something like xposed or magisk installed on top of that to disable the secure flag), but it is absolutely something I'm interested in finding out!

**Comment by pete111** [comment]
thanks abrenoch for your wonderful effort! It would be damn cool to have one app for the whole content on the TV for hyperion. I tried also video grabbing via adb but it does not work on TV - where just software encoded video is grabbed (but works for any content I tried on mobile device, strange).

**Comment by abrenoch** [comment]
Unfortunately I am going to have to bump the minimum SDK up to 21. The `MediaProjection` API was not available until 21, and since that is what I am using to grab the screen I am simply not going to be able to support devices running an earlier version.

Closing this one.
